In [9]:
import numpy as np

student = np.array([67, 78, 92, 74, 65])
student[0]
student[4]
student

array([67, 78, 92, 74, 65])

In [10]:
import pandas as pd

s1 = pd.Series([67, 78, 92, 74, 65], index=["國文","英文", "數學", "地理", "歷史"])
s1

國文    67
英文    78
數學    92
地理    74
歷史    65
dtype: int64

In [11]:
s1 + 3

國文    70
英文    81
數學    95
地理    77
歷史    68
dtype: int64

In [ ]:
s1["國文"] #使用key-index
s1[0] #使用原生索引 index

In [ ]:
for i in s1:
    print(i)

In [ ]:
#numpy的統計，可以套用在pandas
s1

In [21]:
#利用numpy的function做統計
np.sum(s1)

376

In [18]:
np.mean(s1)

75.2

In [19]:
np.std(s1)

9.620810776644555

In [20]:
np.median(s1)

74.0

In [22]:
import pandas as pd

pd.DataFrame({
    "林xx":[78, 92, 76, 91, 72],
    "王xx":[72, 92, 92, 94, 69],
    "張xx":[81, 65, 89, 81, 72],
},index=["國文","英文", "數學", "地理", "歷史"])

    林xx  王xx  張xx
國文   78   72   81
英文   92   92   65
數學   76   92   89
地理   91   94   81
歷史   72   69   72

In [28]:
import numpy as np
import pandas as pd

data = np.random.randint(60, high=100, size=(50,5))
pd.DataFrame(data,
             index = range(1,51),
             columns=["國文","英文", "數學", "地理", "歷史"]
)

    國文  英文  數學  地理  歷史
1   85  69  81  98  80
2   80  86  87  93  79
3   62  85  99  63  75
4   77  65  74  91  97
5   95  73  61  80  98
6   94  84  99  69  65
7   69  84  65  70  84
8   79  86  70  62  94
9   77  78  78  97  94
10  83  67  61  90  78
11  94  77  86  75  90
12  84  91  65  67  96
13  67  99  81  83  72
14  70  79  85  62  71
15  93  92  84  69  64
16  94  86  95  85  85
17  67  89  72  97  89
18  86  67  72  83  99
19  86  67  77  65  94
20  64  61  68  80  96
21  83  84  79  68  66
22  64  90  76  89  79
23  93  65  87  70  69
24  93  82  66  93  88
25  99  71  90  66  60
26  75  80  63  66  81
27  70  71  84  97  87
28  96  93  78  89  78
29  83  86  84  74  84
30  81  74  88  90  68
31  95  77  70  64  89
32  73  64  94  75  88
33  65  94  94  61  67
34  68  84  64  90  88
35  62  60  80  97  92
36  66  76  62  65  72
37  71  84  85  66  64
38  92  66  66  83  90
39  86  73  90  75  90
40  87  92  66  92  64
41  96  76  64  72  98
42  87  86  72  78  87
43  64  97  87  68  86
44  71  94  74  64  66
45  65  99  95  73  75
46  76  80  76  89  97
47  72  96  69  91  99
48  88  92  83  68  65
49  84  73  60  78  86
50  80  74  62  65  62